# Generated by Django 2.0.2 on 2018-11-22 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('askedBy', models.ForeignKey(on_delete=None, related_name='questionProfile', to=settings.AUTH_USER_MODEL)),
                ('intrestedProfile', models.ManyToManyField(related_name='intrestedProfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
