# Generated by Django 2.0.2 on 2018-11-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idyahub', '0006_auto_20181120_1036'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0002_auto_20181122_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('askedBy', models.ForeignKey(on_delete=None, related_name='questionProfile', to=settings.AUTH_USER_MODEL)),
                ('fromHub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idyahub.idyahubInfo')),
                ('intrestedProfile', models.ManyToManyField(blank=True, related_name='intrestedProfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
