# Generated by Django 2.0.2 on 2018-11-22 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('byProfile', models.ForeignKey(on_delete=None, related_name='answeredProfile', to=settings.AUTH_USER_MODEL)),
                ('forQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerForQuestion', to='qna.Question')),
            ],
        ),
    ]
