# Generated by Django 2.0.2 on 2018-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20181122_1326'),
        ('qna', '0006_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='linkedIdya',
        ),
        migrations.AddField(
            model_name='question',
            name='linkedIdya',
            field=models.ManyToManyField(blank=True, to='engine.idya'),
        ),
    ]
