# Generated by Django 2.2.1 on 2019-06-09 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0007_auto_20181122_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answerCount',
            new_name='answer_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='fromHub',
            new_name='hub',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='askedBy',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='intrestedProfile',
        ),
        migrations.RemoveField(
            model_name='question',
            name='linkedIdya',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='question',
            name='curiosity',
            field=models.ManyToManyField(blank=True, related_name='curiousProfiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
