# Generated by Django 2.2.1 on 2019-06-09 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine', '0017_auto_20190609_0539'),
        ('qna', '0008_auto_20190609_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('for_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerThisQuestion', to='qna.Question')),
                ('idya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.idya')),
                ('user', models.ForeignKey(on_delete=None, related_name='answeredProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
