# Generated by Django 2.1 on 2019-06-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0010_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='none', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=250),
        ),
    ]
