# Generated by Django 2.2.2 on 2019-06-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0012_auto_20190622_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=250),
        ),
    ]
