# Generated by Django 2.2.2 on 2019-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0013_auto_20190622_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='curiosity_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
