# Generated by Django 2.0.5 on 2019-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_auto_20190305_2132'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-subscribers_count'], 'verbose_name': 'Channel'},
        ),
        migrations.AddField(
            model_name='channel',
            name='idyas',
            field=models.ManyToManyField(blank=True, related_name='channel_posted_idyas', to='engine.idya'),
        ),
        migrations.AddField(
            model_name='channel',
            name='idyasCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Channel_picture'),
        ),
    ]
