# Generated by Django 2.0.5 on 2019-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20190305_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='channels/channel_picture'),
        ),
    ]
