# Generated by Django 2.2.1 on 2019-05-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20190305_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
