# Generated by Django 2.0.2 on 2018-11-18 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20181118_2048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idyahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idyahub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubAdmin', models.ManyToManyField(related_name='hubAdmin', to=settings.AUTH_USER_MODEL)),
                ('hubIdyas', models.ManyToManyField(blank=True, to='engine.idya')),
                ('members', models.ManyToManyField(blank=True, related_name='hubMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='idyahubinfo',
            old_name='hub_name',
            new_name='hubName',
        ),
        migrations.RenameField(
            model_name='idyahubinfo',
            old_name='hub_pic',
            new_name='hubPic',
        ),
    ]
