# Generated by Django 2.0.2 on 2018-11-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idyahub', '0003_idyahubactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idyahub',
            name='hubAdmin',
        ),
        migrations.RemoveField(
            model_name='idyahub',
            name='hubIdyas',
        ),
        migrations.RemoveField(
            model_name='idyahub',
            name='members',
        ),
        migrations.DeleteModel(
            name='idyahub',
        ),
    ]
