# Generated by Django 2.0.2 on 2018-11-20 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20181120_1034'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idyahub', '0004_auto_20181120_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='idyahub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubAdmin', models.ManyToManyField(related_name='hubAdmin', to=settings.AUTH_USER_MODEL)),
                ('hubIdyas', models.ManyToManyField(blank=True, to='engine.idya')),
                ('hubInfo', models.ForeignKey(on_delete=None, to='idyahub.idyahubInfo')),
                ('members', models.ManyToManyField(blank=True, related_name='hubMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
