# Generated by Django 2.0.2 on 2018-11-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idyahub', '0005_idyahub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idyahubinfo',
            name='is_active',
        ),
        migrations.AddField(
            model_name='idyahub',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
