# Generated by Django 2.2.2 on 2019-06-24 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_auto_20190624_0435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idyahub', '0006_auto_20181120_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedIdya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idyahub.idyahubInfo')),
                ('idya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engine.idya')),
                ('likes', models.ManyToManyField(blank=True, related_name='likesForsharedIdya', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
