# Generated by Django 2.2.2 on 2019-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idyahub', '0007_sharedidya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idyahub',
            name='hubIdyas',
        ),
        migrations.AddField(
            model_name='idyahub',
            name='shared_idya',
            field=models.ManyToManyField(blank=True, to='idyahub.SharedIdya'),
        ),
    ]
