# Generated by Django 2.2.2 on 2019-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0018_auto_20190622_0606'),
        ('idyahub', '0008_auto_20190624_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='idyahub',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='hubQuestion', to='qna.Question'),
        ),
        migrations.AlterField(
            model_name='idyahub',
            name='shared_idya',
            field=models.ManyToManyField(blank=True, related_name='hubIdyas', to='idyahub.SharedIdya'),
        ),
    ]
