# Generated by Django 2.0.2 on 2018-11-18 02:13

from django.conf import settings
from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='idya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idyatype', models.CharField(choices=[('iLog', 'iLog'), ('iMage', 'iMage'), ('iVideo', 'iVideo')], default='iLog', max_length=7)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('Category', 'Category'), ('Business ', 'Business '), ('Marketing  ', 'Marketing  '), ('Literature  ', 'Literature  '), ('Journalism  ', 'Journalism  '), ('Recipes  ', 'Recipes  '), ('Web Design ', 'Web Design '), ('Innovation  ', 'Innovation  '), ('Fashion and Style', 'Fashion and Style'), ('Jobs and Careers ', 'Jobs and Careers '), ('Science ', 'Science '), ('Music ', 'Music '), ('Books ', 'Books '), ('Finance  ', 'Finance  '), ('Entertainment  ', 'Entertainment  '), ('Fiction  ', 'Fiction  '), ('Politics  ', 'Politics  '), ('Web Development ', 'Web Development '), ('Government  ', 'Government  '), ('History ', 'History '), ('Health', 'Health'), ('Economics  ', 'Economics  '), ('Movies ', 'Movies '), ('Physics  ', 'Physics  '), ('Neuroscience  ', 'Neuroscience  '), ('Studying  ', 'Studying  '), ('Philosophy  ', 'Philosophy  '), ('Startups  ', 'Startups  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Friendship  ', 'Friendship  '), ('Learning New Things ', 'Learning New Things '), ('Colleges and Universities ', 'Colleges and Universities '), ('Psychology ', 'Psychology '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Engineering  ', 'Engineering  '), ('Computer Programming ', 'Computer Programming '), ('Research  ', 'Research  '), ('Travel ', 'Travel '), ('Cooking ', 'Cooking '), ('Design ', 'Design '), ('Nutrition  ', 'Nutrition  '), ('Astronomy  ', 'Astronomy  '), ('Technology ', 'Technology '), ('Career Advice ', 'Career Advice '), ('Food ', 'Food '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Blogs  ', 'Blogs  '), ('Others', 'Others'), ('Biology  ', 'Biology  '), ('Television Series ', 'Television Series ')], default='Category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=engine.models.scramble_uploaded_filename, verbose_name='Uploaded image')),
                ('videoUrl', models.URLField(blank=True, null=True)),
                ('likeCount', models.PositiveIntegerField(default=0)),
                ('dislikeCount', models.PositiveIntegerField(default=0)),
                ('from_hub', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=None, related_name='idyaProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
