# Generated by Django 2.0.2 on 2018-11-18 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idyaLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikedProfile', models.ManyToManyField(blank=True, related_name='idya_disliked_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Economics  ', 'Economics  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Movies ', 'Movies '), ('Technology ', 'Technology '), ('Health', 'Health'), ('Biology  ', 'Biology  '), ('Recipes  ', 'Recipes  '), ('Fiction  ', 'Fiction  '), ('Science ', 'Science '), ('Business ', 'Business '), ('Cooking ', 'Cooking '), ('Journalism  ', 'Journalism  '), ('Studying  ', 'Studying  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Learning New Things ', 'Learning New Things '), ('Finance  ', 'Finance  '), ('Friendship  ', 'Friendship  '), ('Marketing  ', 'Marketing  '), ('Nutrition  ', 'Nutrition  '), ('Web Development ', 'Web Development '), ('Books ', 'Books '), ('Music ', 'Music '), ('Psychology ', 'Psychology '), ('Engineering  ', 'Engineering  '), ('Category', 'Category'), ('Food ', 'Food '), ('Entertainment  ', 'Entertainment  '), ('Research  ', 'Research  '), ('Fashion and Style', 'Fashion and Style'), ('History ', 'History '), ('Computer Programming ', 'Computer Programming '), ('Web Design ', 'Web Design '), ('Career Advice ', 'Career Advice '), ('Blogs  ', 'Blogs  '), ('Design ', 'Design '), ('Others', 'Others'), ('Government  ', 'Government  '), ('Travel ', 'Travel '), ('Television Series ', 'Television Series '), ('Startups  ', 'Startups  '), ('Innovation  ', 'Innovation  '), ('Astronomy  ', 'Astronomy  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Literature  ', 'Literature  '), ('Physics  ', 'Physics  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Neuroscience  ', 'Neuroscience  '), ('Philosophy  ', 'Philosophy  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Politics  ', 'Politics  ')], default='Category', max_length=50),
        ),
        migrations.AddField(
            model_name='idyalike',
            name='for_idya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.idya'),
        ),
        migrations.AddField(
            model_name='idyalike',
            name='likedProfile',
            field=models.ManyToManyField(blank=True, related_name='idya_liked_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
