# Generated by Django 2.0.2 on 2018-11-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20181118_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='idya',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Web Design ', 'Web Design '), ('Neuroscience  ', 'Neuroscience  '), ('Design ', 'Design '), ('Fashion and Style', 'Fashion and Style'), ('Philosophy  ', 'Philosophy  '), ('Books ', 'Books '), ('Entertainment  ', 'Entertainment  '), ('Journalism  ', 'Journalism  '), ('Movies ', 'Movies '), ('Politics  ', 'Politics  '), ('Others', 'Others'), ('Physics  ', 'Physics  '), ('Biology  ', 'Biology  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Career Advice ', 'Career Advice '), ('Travel ', 'Travel '), ('History ', 'History '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Science ', 'Science '), ('Engineering  ', 'Engineering  '), ('Innovation  ', 'Innovation  '), ('Government  ', 'Government  '), ('Food ', 'Food '), ('Literature  ', 'Literature  '), ('Economics  ', 'Economics  '), ('Music ', 'Music '), ('Marketing  ', 'Marketing  '), ('Learning New Things ', 'Learning New Things '), ('Astronomy  ', 'Astronomy  '), ('Blogs  ', 'Blogs  '), ('Nutrition  ', 'Nutrition  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Recipes  ', 'Recipes  '), ('Studying  ', 'Studying  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Television Series ', 'Television Series '), ('Fiction  ', 'Fiction  '), ('Friendship  ', 'Friendship  '), ('Computer Programming ', 'Computer Programming '), ('Research  ', 'Research  '), ('Web Development ', 'Web Development '), ('Technology ', 'Technology '), ('Health', 'Health'), ('Business ', 'Business '), ('Cooking ', 'Cooking '), ('Startups  ', 'Startups  '), ('Finance  ', 'Finance  '), ('Category', 'Category'), ('Colleges and Universities ', 'Colleges and Universities '), ('Psychology ', 'Psychology ')], default='Category', max_length=50),
        ),
    ]
