# Generated by Django 2.0.2 on 2018-11-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20181118_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Travel ', 'Travel '), ('Colleges and Universities ', 'Colleges and Universities '), ('Health', 'Health'), ('Psychology ', 'Psychology '), ('Science ', 'Science '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Nutrition  ', 'Nutrition  '), ('Engineering  ', 'Engineering  '), ('Cooking ', 'Cooking '), ('Fashion and Style', 'Fashion and Style'), ('Entertainment  ', 'Entertainment  '), ('Literature  ', 'Literature  '), ('Recipes  ', 'Recipes  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Astronomy  ', 'Astronomy  '), ('Philosophy  ', 'Philosophy  '), ('Biology  ', 'Biology  '), ('Career Advice ', 'Career Advice '), ('Books ', 'Books '), ('Friendship  ', 'Friendship  '), ('Innovation  ', 'Innovation  '), ('Learning New Things ', 'Learning New Things '), ('Food ', 'Food '), ('Journalism  ', 'Journalism  '), ('Computer Programming ', 'Computer Programming '), ('Government  ', 'Government  '), ('Business ', 'Business '), ('Neuroscience  ', 'Neuroscience  '), ('Physics  ', 'Physics  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Technology ', 'Technology '), ('Web Development ', 'Web Development '), ('Blogs  ', 'Blogs  '), ('Studying  ', 'Studying  '), ('Category', 'Category'), ('Finance  ', 'Finance  '), ('Music ', 'Music '), ('Television Series ', 'Television Series '), ('Research  ', 'Research  '), ('Web Design ', 'Web Design '), ('Others', 'Others'), ('Marketing  ', 'Marketing  '), ('Movies ', 'Movies '), ('Economics  ', 'Economics  '), ('Politics  ', 'Politics  '), ('Fiction  ', 'Fiction  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Startups  ', 'Startups  '), ('Design ', 'Design '), ('History ', 'History ')], default='Category', max_length=50),
        ),
    ]
