# Generated by Django 2.0.2 on 2018-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20181118_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Government  ', 'Government  '), ('Literature  ', 'Literature  '), ('Physics  ', 'Physics  '), ('History ', 'History '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Biology  ', 'Biology  '), ('Web Development ', 'Web Development '), ('Innovation  ', 'Innovation  '), ('Nutrition  ', 'Nutrition  '), ('Music ', 'Music '), ('Movies ', 'Movies '), ('Television Series ', 'Television Series '), ('Career Advice ', 'Career Advice '), ('Friendship  ', 'Friendship  '), ('Category', 'Category'), ('Design ', 'Design '), ('Startups  ', 'Startups  '), ('Recipes  ', 'Recipes  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Travel ', 'Travel '), ('Astronomy  ', 'Astronomy  '), ('Health', 'Health'), ('Studying  ', 'Studying  '), ('Finance  ', 'Finance  '), ('Web Design ', 'Web Design '), ('Science ', 'Science '), ('Journalism  ', 'Journalism  '), ('Computer Programming ', 'Computer Programming '), ('Jobs and Careers ', 'Jobs and Careers '), ('Blogs  ', 'Blogs  '), ('Economics  ', 'Economics  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Books ', 'Books '), ('Entertainment  ', 'Entertainment  '), ('Others', 'Others'), ('Psychology ', 'Psychology '), ('Technology ', 'Technology '), ('Fashion and Style', 'Fashion and Style'), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Neuroscience  ', 'Neuroscience  '), ('Cooking ', 'Cooking '), ('Learning New Things ', 'Learning New Things '), ('Food ', 'Food '), ('Politics  ', 'Politics  '), ('Research  ', 'Research  '), ('Fiction  ', 'Fiction  '), ('Engineering  ', 'Engineering  '), ('Business ', 'Business '), ('Marketing  ', 'Marketing  '), ('Philosophy  ', 'Philosophy  ')], default='Category', max_length=50),
        ),
    ]
