# Generated by Django 2.0.2 on 2018-11-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20181120_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Science ', 'Science '), ('Travel ', 'Travel '), ('Philosophy  ', 'Philosophy  '), ('Food ', 'Food '), ('Psychology ', 'Psychology '), ('Cooking ', 'Cooking '), ('Politics  ', 'Politics  '), ('Design ', 'Design '), ('Physics  ', 'Physics  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Health', 'Health'), ('Research  ', 'Research  '), ('Engineering  ', 'Engineering  '), ('Innovation  ', 'Innovation  '), ('Movies ', 'Movies '), ('Technology ', 'Technology '), ('Music ', 'Music '), ('Journalism  ', 'Journalism  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Astronomy  ', 'Astronomy  '), ('Category', 'Category'), ('Marketing  ', 'Marketing  '), ('Computer Programming ', 'Computer Programming '), ('Government  ', 'Government  '), ('Literature  ', 'Literature  '), ('Studying  ', 'Studying  '), ('Startups  ', 'Startups  '), ('Career Advice ', 'Career Advice '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Television Series ', 'Television Series '), ('Biology  ', 'Biology  '), ('Business ', 'Business '), ('Others', 'Others'), ('Entertainment  ', 'Entertainment  '), ('Nutrition  ', 'Nutrition  '), ('Neuroscience  ', 'Neuroscience  '), ('History ', 'History '), ('Economics  ', 'Economics  '), ('Books ', 'Books '), ('Finance  ', 'Finance  '), ('Fiction  ', 'Fiction  '), ('Blogs  ', 'Blogs  '), ('Friendship  ', 'Friendship  '), ('Web Design ', 'Web Design '), ('Recipes  ', 'Recipes  '), ('Web Development ', 'Web Development '), ('Dating and Relationships ', 'Dating and Relationships '), ('Colleges and Universities ', 'Colleges and Universities '), ('Learning New Things ', 'Learning New Things '), ('Fashion and Style', 'Fashion and Style')], default='Category', max_length=50),
        ),
        migrations.AlterField(
            model_name='idya',
            name='from_hub',
            field=models.ForeignKey(on_delete=None, to='idyahub.idyahubInfo'),
        ),
    ]
