# Generated by Django 2.0.2 on 2018-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20181120_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idya',
            options={'ordering': ['-created_at'], 'verbose_name': 'idya'},
        ),
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Engineering  ', 'Engineering  '), ('Journalism  ', 'Journalism  '), ('Economics  ', 'Economics  '), ('Psychology ', 'Psychology '), ('Design ', 'Design '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Nutrition  ', 'Nutrition  '), ('Fiction  ', 'Fiction  '), ('Movies ', 'Movies '), ('Cooking ', 'Cooking '), ('Travel ', 'Travel '), ('Web Design ', 'Web Design '), ('Government  ', 'Government  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Astronomy  ', 'Astronomy  '), ('Blogs  ', 'Blogs  '), ('Recipes  ', 'Recipes  '), ('Others', 'Others'), ('Entertainment  ', 'Entertainment  '), ('Health', 'Health'), ('Startups  ', 'Startups  '), ('Computer Programming ', 'Computer Programming '), ('Physics  ', 'Physics  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Biology  ', 'Biology  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Politics  ', 'Politics  '), ('Fashion and Style', 'Fashion and Style'), ('Music ', 'Music '), ('Research  ', 'Research  '), ('Career Advice ', 'Career Advice '), ('Finance  ', 'Finance  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Studying  ', 'Studying  '), ('Science ', 'Science '), ('Philosophy  ', 'Philosophy  '), ('Technology ', 'Technology '), ('Literature  ', 'Literature  '), ('Learning New Things ', 'Learning New Things '), ('Books ', 'Books '), ('Food ', 'Food '), ('Business ', 'Business '), ('Television Series ', 'Television Series '), ('Friendship  ', 'Friendship  '), ('Marketing  ', 'Marketing  '), ('Neuroscience  ', 'Neuroscience  '), ('Web Development ', 'Web Development '), ('History ', 'History '), ('Innovation  ', 'Innovation  '), ('Category', 'Category')], default='Category', max_length=50),
        ),
    ]
