# Generated by Django 2.0.2 on 2018-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20181122_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Science ', 'Science '), ('Movies ', 'Movies '), ('Technology ', 'Technology '), ('History ', 'History '), ('Politics  ', 'Politics  '), ('Literature  ', 'Literature  '), ('Fiction  ', 'Fiction  '), ('Neuroscience  ', 'Neuroscience  '), ('Fashion and Style', 'Fashion and Style'), ('Jobs and Careers ', 'Jobs and Careers '), ('Astronomy  ', 'Astronomy  '), ('Career Advice ', 'Career Advice '), ('Blogs  ', 'Blogs  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Government  ', 'Government  '), ('Physics  ', 'Physics  '), ('Philosophy  ', 'Philosophy  '), ('Marketing  ', 'Marketing  '), ('Finance  ', 'Finance  '), ('Startups  ', 'Startups  '), ('Web Design ', 'Web Design '), ('Computer Programming ', 'Computer Programming '), ('Business ', 'Business '), ('Others', 'Others'), ('Engineering  ', 'Engineering  '), ('Books ', 'Books '), ('Cooking ', 'Cooking '), ('Research  ', 'Research  '), ('Journalism  ', 'Journalism  '), ('Web Development ', 'Web Development '), ('Health', 'Health'), ('Food ', 'Food '), ('Entertainment  ', 'Entertainment  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Recipes  ', 'Recipes  '), ('Learning New Things ', 'Learning New Things '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Economics  ', 'Economics  '), ('Biology  ', 'Biology  '), ('Music ', 'Music '), ('Nutrition  ', 'Nutrition  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Friendship  ', 'Friendship  '), ('Travel ', 'Travel '), ('Studying  ', 'Studying  '), ('Psychology ', 'Psychology '), ('Design ', 'Design '), ('Innovation  ', 'Innovation  '), ('Television Series ', 'Television Series '), ('Category', 'Category')], default='Category', max_length=50),
        ),
    ]
