# Generated by Django 2.0.5 on 2019-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20181122_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Politics  ', 'Politics  '), ('Computer Programming ', 'Computer Programming '), ('Category', 'Category'), ('Psychology ', 'Psychology '), ('Finance  ', 'Finance  '), ('Physics  ', 'Physics  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Recipes  ', 'Recipes  '), ('Health', 'Health'), ('Cooking ', 'Cooking '), ('Television Series ', 'Television Series '), ('Web Design ', 'Web Design '), ('Jobs and Careers ', 'Jobs and Careers '), ('Dating and Relationships ', 'Dating and Relationships '), ('Fiction  ', 'Fiction  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Neuroscience  ', 'Neuroscience  '), ('Books ', 'Books '), ('Nutrition  ', 'Nutrition  '), ('Government  ', 'Government  '), ('Science ', 'Science '), ('Engineering  ', 'Engineering  '), ('Blogs  ', 'Blogs  '), ('Friendship  ', 'Friendship  '), ('Travel ', 'Travel '), ('Literature  ', 'Literature  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Technology ', 'Technology '), ('Marketing  ', 'Marketing  '), ('Business ', 'Business '), ('Journalism  ', 'Journalism  '), ('Career Advice ', 'Career Advice '), ('Entertainment  ', 'Entertainment  '), ('Biology  ', 'Biology  '), ('Learning New Things ', 'Learning New Things '), ('Movies ', 'Movies '), ('Fashion and Style', 'Fashion and Style'), ('Others', 'Others'), ('History ', 'History '), ('Food ', 'Food '), ('Music ', 'Music '), ('Research  ', 'Research  '), ('Startups  ', 'Startups  '), ('Web Development ', 'Web Development '), ('Studying  ', 'Studying  '), ('Innovation  ', 'Innovation  '), ('Astronomy  ', 'Astronomy  '), ('Economics  ', 'Economics  '), ('Design ', 'Design '), ('Philosophy  ', 'Philosophy  ')], default='Category', max_length=50),
        ),
    ]
