# Generated by Django 2.2.1 on 2019-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_auto_20190305_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idya',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='idya',
            name='from_hub',
        ),
        migrations.RemoveField(
            model_name='idya',
            name='profile',
        ),
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Books ', 'Books '), ('Marketing  ', 'Marketing  '), ('Science ', 'Science '), ('Category', 'Category'), ('Technology ', 'Technology '), ('Food ', 'Food '), ('Travel ', 'Travel '), ('Politics  ', 'Politics  '), ('Movies ', 'Movies '), ('Business ', 'Business '), ('Journalism  ', 'Journalism  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Startups  ', 'Startups  '), ('Research  ', 'Research  '), ('Career Advice ', 'Career Advice '), ('Neuroscience  ', 'Neuroscience  '), ('Music ', 'Music '), ('Government  ', 'Government  '), ('Philosophy  ', 'Philosophy  '), ('Learning New Things ', 'Learning New Things '), ('Blogs  ', 'Blogs  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Finance  ', 'Finance  '), ('Physics  ', 'Physics  '), ('Biology  ', 'Biology  '), ('Literature  ', 'Literature  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Jobs and Careers ', 'Jobs and Careers '), ('Health', 'Health'), ('Others', 'Others'), ('Studying  ', 'Studying  '), ('Innovation  ', 'Innovation  '), ('Design ', 'Design '), ('Dating and Relationships ', 'Dating and Relationships '), ('History ', 'History '), ('Web Design ', 'Web Design '), ('Television Series ', 'Television Series '), ('Fashion and Style', 'Fashion and Style'), ('Friendship  ', 'Friendship  '), ('Computer Programming ', 'Computer Programming '), ('Web Development ', 'Web Development '), ('Fiction  ', 'Fiction  '), ('Recipes  ', 'Recipes  '), ('Engineering  ', 'Engineering  '), ('Astronomy  ', 'Astronomy  '), ('Psychology ', 'Psychology '), ('Entertainment  ', 'Entertainment  '), ('Nutrition  ', 'Nutrition  '), ('Cooking ', 'Cooking '), ('Economics  ', 'Economics  ')], default='Category', max_length=50),
        ),
    ]
