# Generated by Django 2.2.1 on 2019-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channel_description'),
        ('engine', '0013_auto_20190521_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='idya',
            name='channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=None, to='channel.Channel'),
        ),
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Music ', 'Music '), ('Health', 'Health'), ('Science ', 'Science '), ('Business ', 'Business '), ('History ', 'History '), ('Design ', 'Design '), ('Economics  ', 'Economics  '), ('Finance  ', 'Finance  '), ('Books ', 'Books '), ('Marketing  ', 'Marketing  '), ('Recipes  ', 'Recipes  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Studying  ', 'Studying  '), ('Startups  ', 'Startups  '), ('Category', 'Category'), ('Fiction  ', 'Fiction  '), ('Astronomy  ', 'Astronomy  '), ('Travel ', 'Travel '), ('Research  ', 'Research  '), ('Innovation  ', 'Innovation  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Colleges and Universities ', 'Colleges and Universities '), ('Literature  ', 'Literature  '), ('Government  ', 'Government  '), ('Career Advice ', 'Career Advice '), ('Blogs  ', 'Blogs  '), ('Cooking ', 'Cooking '), ('Politics  ', 'Politics  '), ('Neuroscience  ', 'Neuroscience  '), ('Engineering  ', 'Engineering  '), ('Physics  ', 'Physics  '), ('Technology ', 'Technology '), ('Psychology ', 'Psychology '), ('Web Development ', 'Web Development '), ('Entertainment  ', 'Entertainment  '), ('Learning New Things ', 'Learning New Things '), ('Philosophy  ', 'Philosophy  '), ('Journalism  ', 'Journalism  '), ('Nutrition  ', 'Nutrition  '), ('Television Series ', 'Television Series '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Biology  ', 'Biology  '), ('Movies ', 'Movies '), ('Food ', 'Food '), ('Computer Programming ', 'Computer Programming '), ('Web Design ', 'Web Design '), ('Friendship  ', 'Friendship  '), ('Fashion and Style', 'Fashion and Style'), ('Others', 'Others')], default='Category', max_length=50),
        ),
    ]
