# Generated by Django 2.2.1 on 2019-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_auto_20190521_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Technology ', 'Technology '), ('Music ', 'Music '), ('Food ', 'Food '), ('Business ', 'Business '), ('Psychology ', 'Psychology '), ('History ', 'History '), ('Design ', 'Design '), ('Startups  ', 'Startups  '), ('Travel ', 'Travel '), ('Economics  ', 'Economics  '), ('Movies ', 'Movies '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Career Advice ', 'Career Advice '), ('Neuroscience  ', 'Neuroscience  '), ('Science ', 'Science '), ('Physics  ', 'Physics  '), ('Web Development ', 'Web Development '), ('Innovation  ', 'Innovation  '), ('Government  ', 'Government  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Marketing  ', 'Marketing  '), ('Journalism  ', 'Journalism  '), ('Others', 'Others'), ('Engineering  ', 'Engineering  '), ('Studying  ', 'Studying  '), ('Television Series ', 'Television Series '), ('Blogs  ', 'Blogs  '), ('Health', 'Health'), ('Nutrition  ', 'Nutrition  '), ('Research  ', 'Research  '), ('Astronomy  ', 'Astronomy  '), ('Finance  ', 'Finance  '), ('Recipes  ', 'Recipes  '), ('Category', 'Category'), ('Cooking ', 'Cooking '), ('Politics  ', 'Politics  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Philosophy  ', 'Philosophy  '), ('Literature  ', 'Literature  '), ('Books ', 'Books '), ('Fiction  ', 'Fiction  '), ('Web Design ', 'Web Design '), ('Dating and Relationships ', 'Dating and Relationships '), ('Friendship  ', 'Friendship  '), ('Entertainment  ', 'Entertainment  '), ('Biology  ', 'Biology  '), ('Learning New Things ', 'Learning New Things '), ('Fashion and Style', 'Fashion and Style'), ('Computer Programming ', 'Computer Programming ')], default='Category', max_length=50),
        ),
        migrations.AlterField(
            model_name='idya',
            name='channel',
            field=models.ForeignKey(on_delete=None, to='channel.Channel'),
        ),
    ]
