# Generated by Django 2.2.1 on 2019-06-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20190521_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Politics  ', 'Politics  '), ('Television Series ', 'Television Series '), ('Travel ', 'Travel '), ('Fashion and Style', 'Fashion and Style'), ('Philosophy  ', 'Philosophy  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Startups  ', 'Startups  '), ('Neuroscience  ', 'Neuroscience  '), ('Physics  ', 'Physics  '), ('Recipes  ', 'Recipes  '), ('Biology  ', 'Biology  '), ('Fiction  ', 'Fiction  '), ('Web Design ', 'Web Design '), ('Studying  ', 'Studying  '), ('Government  ', 'Government  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Career Advice ', 'Career Advice '), ('Health', 'Health'), ('Entertainment  ', 'Entertainment  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Research  ', 'Research  '), ('Innovation  ', 'Innovation  '), ('Movies ', 'Movies '), ('Music ', 'Music '), ('Finance  ', 'Finance  '), ('Science ', 'Science '), ('Design ', 'Design '), ('Jobs and Careers ', 'Jobs and Careers '), ('Engineering  ', 'Engineering  '), ('Food ', 'Food '), ('Category', 'Category'), ('Literature  ', 'Literature  '), ('Learning New Things ', 'Learning New Things '), ('Nutrition  ', 'Nutrition  '), ('Blogs  ', 'Blogs  '), ('Journalism  ', 'Journalism  '), ('Technology ', 'Technology '), ('Economics  ', 'Economics  '), ('Psychology ', 'Psychology '), ('History ', 'History '), ('Marketing  ', 'Marketing  '), ('Web Development ', 'Web Development '), ('Astronomy  ', 'Astronomy  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Others', 'Others'), ('Books ', 'Books '), ('Business ', 'Business '), ('Computer Programming ', 'Computer Programming '), ('Cooking ', 'Cooking '), ('Friendship  ', 'Friendship  ')], default='Category', max_length=50),
        ),
    ]
