# Generated by Django 2.2.2 on 2019-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20190609_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Science ', 'Science '), ('Business ', 'Business '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Fiction  ', 'Fiction  '), ('Jobs and Careers ', 'Jobs and Careers '), ('Career Advice ', 'Career Advice '), ('Technology ', 'Technology '), ('History ', 'History '), ('Philosophy  ', 'Philosophy  '), ('Television Series ', 'Television Series '), ('Research  ', 'Research  '), ('Web Development ', 'Web Development '), ('Web Design ', 'Web Design '), ('Movies ', 'Movies '), ('Physics  ', 'Physics  '), ('Engineering  ', 'Engineering  '), ('Politics  ', 'Politics  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Learning New Things ', 'Learning New Things '), ('Cooking ', 'Cooking '), ('Nutrition  ', 'Nutrition  '), ('Studying  ', 'Studying  '), ('Psychology ', 'Psychology '), ('Entertainment  ', 'Entertainment  '), ('Government  ', 'Government  '), ('Health', 'Health'), ('Design ', 'Design '), ('Others', 'Others'), ('Economics  ', 'Economics  '), ('Finance  ', 'Finance  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Biology  ', 'Biology  '), ('Food ', 'Food '), ('Marketing  ', 'Marketing  '), ('Recipes  ', 'Recipes  '), ('Blogs  ', 'Blogs  '), ('Friendship  ', 'Friendship  '), ('Category', 'Category'), ('Music ', 'Music '), ('Books ', 'Books '), ('Literature  ', 'Literature  '), ('Journalism  ', 'Journalism  '), ('Startups  ', 'Startups  '), ('Computer Programming ', 'Computer Programming '), ('Neuroscience  ', 'Neuroscience  '), ('Innovation  ', 'Innovation  '), ('Dating and Relationships ', 'Dating and Relationships '), ('Travel ', 'Travel '), ('Astronomy  ', 'Astronomy  '), ('Fashion and Style', 'Fashion and Style')], default='Category', max_length=50),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('idya', models.ManyToManyField(blank=True, null=True, related_name='idyaUnderThisCategory', to='engine.idya')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
    ]
