# Generated by Django 2.2.2 on 2019-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_auto_20190623_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='idya',
            field=models.ManyToManyField(blank=True, related_name='idyaUnderThisCategory', to='engine.idya'),
        ),
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Movies ', 'Movies '), ('Jobs and Careers ', 'Jobs and Careers '), ('Technology ', 'Technology '), ('Others', 'Others'), ('Psychology ', 'Psychology '), ('Journalism  ', 'Journalism  '), ('Physics  ', 'Physics  '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Travel ', 'Travel '), ('Economics  ', 'Economics  '), ('Books ', 'Books '), ('Nutrition  ', 'Nutrition  '), ('Recipes  ', 'Recipes  '), ('Learning New Things ', 'Learning New Things '), ('Blogs  ', 'Blogs  '), ('Health', 'Health'), ('Computer Programming ', 'Computer Programming '), ('Innovation  ', 'Innovation  '), ('Neuroscience  ', 'Neuroscience  '), ('Research  ', 'Research  '), ('Design ', 'Design '), ('Web Development ', 'Web Development '), ('Government  ', 'Government  '), ('Politics  ', 'Politics  '), ('Web Design ', 'Web Design '), ('Career Advice ', 'Career Advice '), ('Category', 'Category'), ('Entertainment  ', 'Entertainment  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Fiction  ', 'Fiction  '), ('Friendship  ', 'Friendship  '), ('Philosophy  ', 'Philosophy  '), ('Marketing  ', 'Marketing  '), ('History ', 'History '), ('Fashion and Style', 'Fashion and Style'), ('Finance  ', 'Finance  '), ('Television Series ', 'Television Series '), ('Literature  ', 'Literature  '), ('Startups  ', 'Startups  '), ('Business ', 'Business '), ('Engineering  ', 'Engineering  '), ('Studying  ', 'Studying  '), ('Astronomy  ', 'Astronomy  '), ('Colleges and Universities ', 'Colleges and Universities '), ('Food ', 'Food '), ('Cooking ', 'Cooking '), ('Biology  ', 'Biology  '), ('Music ', 'Music '), ('Dating and Relationships ', 'Dating and Relationships '), ('Science ', 'Science ')], default='Category', max_length=50),
        ),
    ]
