# Generated by Django 2.2.2 on 2019-06-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_auto_20190623_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idya',
            name='category',
            field=models.CharField(choices=[('Design ', 'Design '), ('Music ', 'Music '), ('Food ', 'Food '), ('History ', 'History '), ('Startups  ', 'Startups  '), ('Recipes  ', 'Recipes  '), ('Web Design ', 'Web Design '), ('Category', 'Category'), ('Psychology ', 'Psychology '), ('Health', 'Health'), ('Fashion and Style', 'Fashion and Style'), ('Entertainment  ', 'Entertainment  '), ('Literature  ', 'Literature  '), ('Physics  ', 'Physics  '), ('Nutrition  ', 'Nutrition  '), ('Learning New Things ', 'Learning New Things '), ('Engineering  ', 'Engineering  '), ('Studying  ', 'Studying  '), ('Innovation  ', 'Innovation  '), ('Computer Programming ', 'Computer Programming '), ('Friendship  ', 'Friendship  '), ('Research  ', 'Research  '), ('Politics  ', 'Politics  '), ('Career Advice ', 'Career Advice '), ('Entrepreneurship  ', 'Entrepreneurship  '), ('Web Development ', 'Web Development '), ('Jobs and Careers ', 'Jobs and Careers '), ('Colleges and Universities ', 'Colleges and Universities '), ('Others', 'Others'), ('Technology ', 'Technology '), ('Economics  ', 'Economics  '), ('Science of Everyday Life ', 'Science of Everyday Life '), ('Dating and Relationships ', 'Dating and Relationships '), ('Biology  ', 'Biology  '), ('Science ', 'Science '), ('Neuroscience  ', 'Neuroscience  '), ('Books ', 'Books '), ('Movies ', 'Movies '), ('Marketing  ', 'Marketing  '), ('Astronomy  ', 'Astronomy  '), ('Blogs  ', 'Blogs  '), ('Cooking ', 'Cooking '), ('Philosophy  ', 'Philosophy  '), ('Travel ', 'Travel '), ('Finance  ', 'Finance  '), ('Television Series ', 'Television Series '), ('Fiction  ', 'Fiction  '), ('Journalism  ', 'Journalism  '), ('Business ', 'Business '), ('Government  ', 'Government  ')], default='Category', max_length=50),
        ),
    ]
