# Generated by Django 2.0.2 on 2018-11-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend_count',
        ),
    ]
