# Generated by Django 2.0.2 on 2018-11-17 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_friend_friend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='friendRequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friendList', to=settings.AUTH_USER_MODEL),
        ),
    ]
