# Generated by Django 2.0.2 on 2018-11-18 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20181118_2010'),
        ('account', '0006_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='idyaBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_idyas', models.ManyToManyField(related_name='bookmarks', to='engine.idya')),
                ('for_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileIdyaBookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
