# Generated by Django 2.0.2 on 2018-11-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_idyabookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedidyahub',
            name='hubs',
            field=models.ManyToManyField(blank=True, related_name='subscribedHubs', to='idyahub.idyahubInfo'),
        ),
        migrations.AlterField(
            model_name='subscribedidyahub',
            name='invites',
            field=models.ManyToManyField(blank=True, to='idyahub.idyahubInfo'),
        ),
    ]
